### ISSUE TITLE
Link project board

### ISSUE THREAD

**Issue by johnsickels** [brobuck87/perfect-espresso-tool#2]
- go to https://github.com/brobuck87/Perfect-Espresso-Tool
- click on Projects tab
- search for the new "Perfect Espresso" project board

<img width="1195" alt="Screen Shot 2022-08-12 at 3 44 58 PM" src="https://user-images.githubusercontent.com/46609057/184432025-2037a427-b62b-40e4-aa67-778d93c18e3d.png">

**Comment by johnsickels** [comment]
I think you can add a project that I made here. According to these docs:
https://docs.github.com/en/github-ae@latest/issues/organizing-your-work-with-project-boards/managing-project-boards/linking-a-repository-to-a-project-board

> Anyone with write permissions to a project board can link repositories owned by that organization or personal account to the project board.

**Comment by brobuck87** [comment]
Created the project board
